SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
        SUM(PRICE * SALES) TOTAL_PRICE
FROM (
    SELECT *
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'  -- LIKE문 사용 가능
    ) BS
LEFT JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;
