-- 코드를 작성해주세요
SELECT A.ID, 
        (CASE  
        WHEN (PER <= 0.25) THEN 'CRITICAL'
        WHEN (PER >0.25 AND PER <= 0.5) THEN 'HIGH'
        WHEN (PER <= 0.75) THEN 'MEDIUM'
        ELSE 'LOW'
        END) AS COLONY_NAME
FROM ECOLI_DATA A 
    JOIN (SELECT ID,
          PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS PER
          FROM ECOLI_DATA) ET
    ON A.ID = ET.ID
ORDER BY A.ID;