SELECT YEAR(DIFFERENTIATION_DATE) YEAR, 
        (MAX_YEAR - SIZE_OF_COLONY) YEAR_DEV, 
        ID
FROM (SELECT *, 
      MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) MAX_YEAR
      FROM ECOLI_DATA
     ) A
ORDER BY YEAR, YEAR_DEV

